### ISSUE TITLE
Cool software

### ISSUE THREAD

**Issue by ghost** [jcg/d-tailor#1]
Even in 2018, your software still looks awesome.

I would like to play around with it, however I have a problem with the license of UNAFold.

Do you need UNAfold for the structure prediction or can Vienna RNA take over? As demonstrated in " Evaluation of ..." the structure is really important, so it makes sense that I would need the structure to get most of the software.

BR,
pieter

**Comment by jcg** [comment]
Hi Pieter,

thanks for the very kind words. At the time we built the software UNAFold was still open source and free of charge, which unfortunately it's not the case anymore.

Thus, the most wise thing to do would be to reimplement the structure prediction feature using the Vienna RNA package instead of UNAFold as you suggested. It should be relatively straightforward and II will try to find some time to implement this in the near future.

Best,
Joao

**Comment by ghost** [comment]
Very nice. Thanks!

**Comment by ghost** [comment]
Will this be possible? Any progress?
I'm a bit reculant to try it myself, as it doesn't seem that obvious for me.
If you could give me pointers were to look/start, that would be nice...
Best regards,
Pieter

**Comment by jcg** [comment]
There is now a new branch "dtailor-rnafold" where you can use RNA structure/duplex prediction feature within D-Tailor using Vienna RNA package (free software) instead of UNAfold.

You can find the Vienna RNA package at https://www.tbi.univie.ac.at/RNA/#download 

After installation, copy the relevant binaries to 3rdParty/vienna

Let me know if you have any issues.
